###
GET http://localhost:3000/empleados

###
POST http://localhost:3000/empleados
Content-Type: application/json

{
    "nombre":"Paco",
    "puesto":"Jefe de Sistemas",
    "email":"paco@disney.com",
    "sueldo": 15000
}

###
DELETE http://localhost:3000/empleados/62c3301c2e06be14b198b8c2

###
GET http://localhost:3000/empleados/62c32f9b2e06be14b198b8bd

###
PUT http://localhost:3000/empleados/62c3301c2e06be14b198b8c2
Content-Type: application/json

{
    "puesto":"Programador",
    "sueldo":18000
}