###
GET http://localhost:3000/empleados/

###
POST http://localhost:3000/empleados
Content-Type: application/json

{
    "nombre":"Pedro Picapiedra",
    "puesto":"Programador Sr.",
    "email":"pedropicapiedra@disney.com",
    "sueldo": 15
}

###
DELETE http://localhost:3000/empleados/8

###
GET http://localhost:3000/empleados/4

###
PUT http://localhost:3000/empleados/17
Content-Type: application/json

{
    "puesto":"Gerente de Sistemas.",
    "sueldo":50000
}